export const Api = {
  dashboard: '/api/admin/dashboard',
  getBrandsList: '/api/list/brands',
  createBrand: '/api/brand/create',
  updateBrand: '/api/brand/update',
  deleteBrand: '/api/brand/delete',
  getCdtCodesList: '/api/list/cdt-codes',
  createCdtCode: '/api/cdt-code/create',
  updateCdtCode: '/api/cdt-code/update',
  deleteCdtCode: '/api/cdt-code/delete',
  getItemsList: '/api/list/items',
  createItem: '/api/item/create',
  updateItem: '/api/item/update',
  deleteItem: '/api/item/delete',
  getProceduresList: '/api/list/procedures',
  createProcedure: '/api/procedure/create',
  updateProcedure: '/api/procedure/update',
  deleteProcedure: '/api/procedure/delete',
  getProcedureTemplatesList: '/api/list/procedure-templates',
  createProcedureTemplate: '/api/procedure-template/create',
  updateProcedureTemplate: '/api/procedure-template/update',
  deleteProcedureTemplate: '/api/procedure-template/delete',
  getInventoryList: '/api/list/inventory',
  createInventory: '/api/inventory/create',
  updateInventory: '/api/inventory/update',
  deleteInventory: '/api/inventory/delete',
  restockItem: '/api/restock',
}
